services:
  db:
    image: postgres:13 # j'ai préféré utiliser l'image postgres au lieu d'installer pgadmin sur mon ordi
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5482:5432"
  
  app:
    build: .
    depends_on:
      - db
    volumes:
      - ./data:/data
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase

  pgadmin:
    container_name: csv_to_postgres_pipeline
    image: dpage/pgadmin4 # a partir de pg admin, je peux acceder à l'interface d'administration pour voir mes données
    environment:
      PGADMIN_DEFAULT_EMAIL: debug@debug.com
      PGADMIN_DEFAULT_PASSWORD: debug
    ports:
      - "5557:80"
    restart: always

  docs:
    image: minidocks/mkdocs:latest # avec minidocks, j'ai voulu faire une petite documentation xD :)
    container_name: mkdocs
    volumes:
      - ./docs/:/docs 
    restart: always
    ports:
      - "9026:9000"
    stdin_open: true
    tty: true
    command: mkdocs serve --config-file /docs/mkdocs.yml --dev-addr 0.0.0.0:9000
